### ISSUE TITLE
what is this and will it be in English?

### ISSUE THREAD

**Issue by erikkaplun** [ZilvinasKucinskas/FRP-EventSourcing#1]
The title seems compelling but not compelling enough to teach myself Lithuanian yet...

I'm working on similar stuff (programming not books) so I'd be quite intersted to find out what this repository contains.

**Comment by ZilvinasKucinskas** [comment]
@eallik Sorry for late answer, currently quite busy working with 2 startups.

This is my Master's thesis. I have a plan to continue it from September 2016. 

Main idea:
- Prooving that you can combine EventSourcing with FRP
- FRP theory + CQRS + EventSourcing theory. (CQRS and EventSourcing was my Bachelor thesis, in which I contacted live with Greg Young and got personal session with him)
- Use Functional Reactive Programming concepts and syntax while transparently saving events to some kind of storage (for example File System, MongoDB or any other). 
- Ability to reply those events through event streams.
- Create DSL (thinking about ELM or Scala for example) enabling to:
  a) Create event streams
  b) Combine event streams
  c) Filter event streams
  while transparently saving those events as a history log.

If this is some kind of interest for you or some other people following this repository, I could actually translate whole thesis to english in a summer.
I wonder if there would be any contributor willing to read it and make contributions (Open Source Master Thesis).

I would be glad to hear is that some kind similar to what you are doing. Maybe you can link a repository I can look at. Any comments at this point is highly desirable.
